name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci
  FOUNDRY_ETH_RPC_URL: ${{ secrets.RPC_URL }}

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install deps
        run: forge install

      - name: Run tests
        run: |
          touch .env 
          echo FOUNDRY_ETH_RPC_URL=${{ secrets.RPC_URL }} >> .env 
          npm run test
